name: dend
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==3.5.4
    - numpy==1.13.1
    - matplotlib==2.2.2
    - jupyter==1.0.0
    - pyodbc==3.0.10
    - Pillow==5.0.0
    - scikit-learn
    - scikit-image
    - scipy==0.19.1
    - pymongo==3.4.0
    - PyYAML==3.12
    - pandas==0.22.0
    - pywin32==220
    - beautifulsoup4==4.6.0
    - celery==4.1.0
    - CherryPy==14.0.0
    - Cython==0.28.1
    - future==0.16.0
    - lxml==4.2.0
    - pika==0.11.2
    - mkl-service
    - keyring==9.3.1
    - requests==2.18.4
    - nose
    - openpyxl
    - paramiko==2.4.1
    - pyspark
    - pip:
        - Flask-Session==0.3.1
        - Flask-Caching==1.3.3
        - dateparser
        - TextBlob
